// core/memory — typed memory public index (ACBP-P2-006; CDR-024). Cross-module imports go through this index.
export {
  createMemoryItem,
  listMemoryItems,
  editMemoryItem,
  getMemoryItem,
  deleteMemoryItem,
  MEMORY_LIST_DEFAULT_LIMIT,
  MEMORY_LIST_MAX_LIMIT,
  type CreateMemoryItemParams,
  type ListMemoryItemsParams,
  type EditMemoryItemParams,
  type GetMemoryItemParams,
  type DeleteMemoryItemParams,
  type MemoryOptions,
  type CreateMemoryItemResult,
  type ListMemoryItemsResult,
  type EditMemoryItemResult,
  type GetMemoryItemResult,
  type DeleteMemoryItemResult,
} from './memory-item.js';
