# ACBP-P0-021 - local PostgreSQL via a DEDICATED, isolated WSL distro (Windows primary path).
#
# Route: WSL-hosted PostgreSQL 16, proven on this machine in P0-018 (Docker Desktop is NOT required).
# Creates a dedicated distro 'acbp-local-dev' - it never touches docker-desktop, OpenClawGateway, or
# any other distro. Separates a LONG-LIVED dev database (acbp_dev) from a DISPOSABLE integration-test
# database (acbp_test). Credentials are generated in memory, passed to WSL via WSLENV (never on a
# command line), written only to a git-ignored .env.local, and NEVER printed. Local-only (127.0.0.1).
#
# Usage:
#   powershell -File tools/local/db.ps1 -Action setup          # provision distro + PG16 + DBs + .env.local
#   powershell -File tools/local/db.ps1 -Action start|stop|status
#   powershell -File tools/local/db.ps1 -Action reset -Force   # drop+recreate the TEST db (requires -Force)
[CmdletBinding()]
param(
  [ValidateSet('setup', 'start', 'stop', 'status', 'reset')]
  [string]$Action = 'status',
  [switch]$Force
)
$ErrorActionPreference = 'Stop'
# Ensure text piped to native commands (wsl/bash stdin) is UTF-8 WITHOUT a BOM.
$OutputEncoding = New-Object System.Text.UTF8Encoding $false
$DISTRO = 'acbp-local-dev'
$PROTECTED = @('docker-desktop', 'OpenClawGateway')

# --- repository-root guard (portable; rejects Halo paths) ------------------------------------------
$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
if ($repoRoot -match 'halo-suite') { throw "Refusing to run inside a Halo path: $repoRoot" }
$pkg = Get-Content (Join-Path $repoRoot 'package.json') -Raw | ConvertFrom-Json
if ($pkg.name -ne 'ai-company-builder-platform') { throw "Not the ACBP repository root: $repoRoot" }
if ($PROTECTED -contains $DISTRO) { throw "Dedicated distro name collides with a protected distro." }

function Test-DistroExists {
  (wsl --list --quiet 2>$null | ForEach-Object { ($_ -replace "`0", '').Trim() }) -contains $DISTRO
}

# Run a bash command in the dedicated distro as root. Base64-encoded so no BOM/quoting/CR issues can
# reach bash (PowerShell can prepend a BOM when piping to a native command's stdin).
function Invoke-Pg([string]$bash) {
  $b64 = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes(($bash -replace "`r`n", "`n")))
  wsl -d $DISTRO -u root -- bash -c "echo $b64 | base64 -d | bash"
}

# Convert the Windows repo path to a /mnt WSL path.
function Get-WslRepoPath {
  '/mnt/' + $repoRoot.Substring(0, 1).ToLower() + ($repoRoot.Substring(2) -replace '\\', '/')
}

switch ($Action) {
  'setup' {
    if (Test-DistroExists) {
      Write-Host "distro '$DISTRO' already present"
    }
    else {
      Write-Host "installing dedicated distro '$DISTRO' (Ubuntu-24.04)..."
      wsl --install -d Ubuntu-24.04 --name $DISTRO --no-launch
      if ($LASTEXITCODE -ne 0) { throw "failed to create dedicated WSL distro '$DISTRO'" }
    }
    $chars = (48..57) + (65..90) + (97..122)
    $pw = -join (1..32 | ForEach-Object { [char]($chars | Get-Random) })
    $env:ACBP_PW = $pw
    $env:WSLENV = 'ACBP_PW/u'
    $prov = (Get-WslRepoPath) + '/tools/local/provision.sh'
    Write-Host "provisioning PostgreSQL 16 + dev/test databases in '$DISTRO'..."
    $out = wsl -d $DISTRO -u root -- bash -c "tr -d '\r' < '$prov' | bash"
    $env:ACBP_PW = $null
    if ($out -notmatch 'SETUP_OK') { throw "database provisioning failed in '$DISTRO'" }
    # Write git-ignored .env.local (values never printed).
    $devUrl = "postgresql://acbp_dev:$pw@127.0.0.1:5432/acbp_dev"
    $testUrl = "postgresql://acbp_dev:$pw@127.0.0.1:5432/acbp_test"
    $body = @(
      '# ACBP local development env - generated by tools/local/db.ps1 (ACBP-P0-021).',
      '# GIT-IGNORED (.env.*). Never commit. Local fakes only; never real/staging/production values.',
      'APP_ENV=development',
      'DATABASE_SSL=disable',
      "DATABASE_URL=$devUrl",
      "ACBP_TEST_DATABASE_URL=$testUrl"
    ) -join "`n"
    [IO.File]::WriteAllText((Join-Path $repoRoot '.env.local'), $body + "`n", (New-Object Text.UTF8Encoding($false)))
    Remove-Variable pw
    Write-Host "wrote .env.local (DATABASE_URL, ACBP_TEST_DATABASE_URL) - values not shown"
    Write-Host "setup complete: dev db 'acbp_dev' (long-lived) + test db 'acbp_test' (disposable) on 127.0.0.1:5432"
  }
  'start' {
    if (-not (Test-DistroExists)) { throw "distro '$DISTRO' not found - run: db.ps1 -Action setup" }
    Invoke-Pg 'pg_ctlcluster 16 main start 2>/dev/null || service postgresql start 2>/dev/null || true; pg_isready -h 127.0.0.1 -p 5432'
  }
  'stop' {
    if (Test-DistroExists) {
      Invoke-Pg 'pg_ctlcluster 16 main stop 2>/dev/null || service postgresql stop 2>/dev/null || true; echo stopped' | Out-Null
      wsl --terminate $DISTRO 2>$null | Out-Null
      Write-Host "stopped (distro '$DISTRO' preserved, not unregistered)"
    }
    else { Write-Host "distro '$DISTRO' not present" }
  }
  'status' {
    if (-not (Test-DistroExists)) { Write-Host "distro '$DISTRO': not installed"; break }
    Invoke-Pg 'pg_isready -h 127.0.0.1 -p 5432 || true; echo databases:; sudo -u postgres psql -tAc "SELECT datname FROM pg_database WHERE datname IN (''acbp_dev'',''acbp_test'') ORDER BY datname" 2>/dev/null'
  }
  'reset' {
    if (-not $Force) { throw "reset is destructive - re-run with -Force to drop+recreate the TEST database (acbp_test)" }
    if (-not (Test-DistroExists)) { throw "distro '$DISTRO' not found" }
    Invoke-Pg 'sudo -u postgres psql -v ON_ERROR_STOP=1 -q -c "DROP DATABASE IF EXISTS acbp_test;" -c "CREATE DATABASE acbp_test OWNER acbp_dev;"; echo RESET_OK' | Out-Null
    Write-Host "reset complete: test database 'acbp_test' recreated (dev database 'acbp_dev' untouched)"
  }
}
