// @acbp/planning contracts (ACBP-P4-001; CDR-039; ROAD-001/002). Provider- and framework-neutral, zero-dep.
//
// The roadmap is the DECIDED strategy turned into a plan: goals + milestones sequenced by ORDER (never by invented
// dates — ADR-019 forbids fake precision). Roadmaps are VERSIONED append-only: a new version is a new row, never an
// in-place edit, which is what makes ROAD-002's "version write failure blocks the edit rather than losing history"
// structural. Parsing is deny-by-default; the `partial` flag is honest labeling, NOT a failure channel (CDR-029's
// rule: a gateway failure or malformed output persists nothing — only a successfully-parsed, model-flagged output is
// `partial`). P4-001 plans NO tasks (task generation is P4-003).

const FAIL = { ok: false } as const;

/** A roadmap version is complete, or honestly labeled partial when the model itself flagged it (ROAD-001). */
export const ROADMAP_STATUSES = ['complete', 'partial'] as const;
export type RoadmapStatus = (typeof ROADMAP_STATUSES)[number];
export function isRoadmapStatus(v: unknown): v is RoadmapStatus {
  return typeof v === 'string' && (ROADMAP_STATUSES as readonly string[]).includes(v);
}

/** How a version came to exist: generated by the model, or authored by an owner edit (ROAD-002). */
export const ROADMAP_ORIGINS = ['generated', 'edited'] as const;
export type RoadmapOrigin = (typeof ROADMAP_ORIGINS)[number];
export function isRoadmapOrigin(v: unknown): v is RoadmapOrigin {
  return typeof v === 'string' && (ROADMAP_ORIGINS as readonly string[]).includes(v);
}

/** Goal lifecycle (DATA-ARCHITECTURE). No transition path exists yet — CDR-039 §7-G4. */
export const GOAL_STATUSES = ['active', 'achieved', 'dropped'] as const;
export type GoalStatus = (typeof GOAL_STATUSES)[number];

/** Milestone lifecycle (DATA-ARCHITECTURE). No transition path exists yet — CDR-039 §7-G4. */
export const MILESTONE_STATUSES = ['planned', 'reached', 'dropped'] as const;
export type MilestoneStatus = (typeof MILESTONE_STATUSES)[number];

/** The gateway output-schema ref for roadmap planning (the composition dispatches validateOutput on it). */
export const ROADMAP_SCHEMA = 'planning.roadmap.output@1';

export const PLAN_TITLE_MAX = 200;
export const PLAN_DESCRIPTION_MAX = 4_000;
export const EDIT_REASON_MAX = 4_000;
/** A roadmap must plan something; an empty plan is not an honest partial, it is no plan at all. */
export const PLAN_ITEMS_MAX = 50;

/** One planned goal, as parsed from the model or supplied by an owner edit. Ordinals are assigned by the platform. */
export interface PlanItemInput {
  readonly title: string;
  readonly description: string | null;
}
/** A milestone additionally MAY name the goal it serves, by that goal's ordinal (CDR-039 §7-G5). */
export interface MilestoneInput extends PlanItemInput {
  readonly goalOrdinal: number | null;
}

export interface RoadmapOutput {
  readonly goals: readonly PlanItemInput[];
  readonly milestones: readonly MilestoneInput[];
  readonly partial: boolean;
}
export type RoadmapParse = { readonly ok: true; readonly value: RoadmapOutput } | { readonly ok: false };

/** Trim + bound a title. Returns undefined when unusable (absent, blank, non-string, or over-long) — deny-by-default. */
function title(v: unknown): string | undefined {
  if (typeof v !== 'string') return undefined;
  const t = v.trim();
  return t.length === 0 || t.length > PLAN_TITLE_MAX ? undefined : t;
}
/** Trim + bound an optional description. `null` when absent/blank; `undefined` when present but unusable. */
function description(v: unknown): string | null | undefined {
  if (v === undefined || v === null) return null;
  if (typeof v !== 'string') return undefined;
  const t = v.trim();
  if (t.length > PLAN_DESCRIPTION_MAX) return undefined;
  return t.length === 0 ? null : t;
}

/**
 * The invariants a roadmap must satisfy to be PERSISTABLE, applied identically by the raw parse and by the defensive
 * re-entry so the two can never drift (a weaker backstop would let a caller that wires a different gateway validator
 * persist a plan the parser exists to reject).
 *
 * - An EMPTY plan is not an honest partial — there is nothing to persist.
 * - A plan missing EITHER side (no goals, or no milestones) may only be labeled `partial`: ROAD-001's acceptance is a
 *   roadmap that contains goals AND sequenced milestones, so a one-sided plan can never be `complete`.
 * - Bounded sizes, so a plan can never exceed what the DB CHECKs accept (a length that only the DB rejects would
 *   surface as a raw constraint error instead of an honest `generation_failed`).
 */
function roadmapShapeOk(goals: readonly PlanItemInput[], milestones: readonly MilestoneInput[], partial: boolean): boolean {
  if (goals.length === 0 && milestones.length === 0) return false;
  if ((goals.length === 0 || milestones.length === 0) && !partial) return false;
  if (goals.length > PLAN_ITEMS_MAX || milestones.length > PLAN_ITEMS_MAX) return false;
  for (const item of [...goals, ...milestones]) {
    if (item.title.length === 0 || item.title.length > PLAN_TITLE_MAX) return false;
    if (item.description !== null && (item.description.length === 0 || item.description.length > PLAN_DESCRIPTION_MAX)) return false;
  }
  for (const m of milestones) {
    if (m.goalOrdinal !== null && (!Number.isInteger(m.goalOrdinal) || m.goalOrdinal < 0 || m.goalOrdinal >= goals.length)) return false;
  }
  return true;
}

/**
 * Parse the gateway's roadmap output (the gateway shape-validator). DENY-BY-DEFAULT: any malformed member rejects the
 * WHOLE payload rather than silently dropping it — a partially-understood plan must never be presented as a plan.
 *
 * A `goalOrdinal` on a milestone must reference a goal that is actually present, so a milestone can never dangle.
 * The `partial` flag is parsed strictly (absent → complete; non-boolean → reject, never coerced) so an honest partial
 * label can only come from the model deliberately setting it.
 */
export function parseRoadmapOutput(raw: string): RoadmapParse {
  let root: unknown;
  try {
    root = JSON.parse(raw);
  } catch {
    return FAIL;
  }
  if (typeof root !== 'object' || root === null || Array.isArray(root)) return FAIL;
  const obj = root as { goals?: unknown; milestones?: unknown; partial?: unknown };

  const rawPartial = obj.partial;
  if (rawPartial !== undefined && typeof rawPartial !== 'boolean') return FAIL;
  const partial = rawPartial === true;

  if (!Array.isArray(obj.goals) || !Array.isArray(obj.milestones)) return FAIL;

  const goals: PlanItemInput[] = [];
  for (const g of obj.goals) {
    if (typeof g !== 'object' || g === null) return FAIL;
    const t = title((g as { title?: unknown }).title);
    const d = description((g as { description?: unknown }).description);
    if (t === undefined || d === undefined) return FAIL;
    goals.push({ title: t, description: d });
  }

  const milestones: MilestoneInput[] = [];
  for (const m of obj.milestones) {
    if (typeof m !== 'object' || m === null) return FAIL;
    const t = title((m as { title?: unknown }).title);
    const d = description((m as { description?: unknown }).description);
    if (t === undefined || d === undefined) return FAIL;
    const rawOrdinal = (m as { goal_ordinal?: unknown }).goal_ordinal;
    let goalOrdinal: number | null = null;
    if (rawOrdinal !== undefined && rawOrdinal !== null) {
      // A named goal must exist in THIS payload — a dangling reference rejects the whole plan.
      if (typeof rawOrdinal !== 'number' || !Number.isInteger(rawOrdinal) || rawOrdinal < 0 || rawOrdinal >= goals.length) return FAIL;
      goalOrdinal = rawOrdinal;
    }
    milestones.push({ title: t, description: d, goalOrdinal });
  }

  if (!roadmapShapeOk(goals, milestones, partial)) return FAIL;
  return { ok: true, value: { goals, milestones, partial } };
}

/**
 * Defensively re-enter the gateway's ALREADY-VALIDATED output (camelCase, produced by parseRoadmapOutput at the
 * gateway seam). No raw re-parse — a corrupted seam value yields undefined, which the caller treats as a failure.
 *
 * It re-applies the SAME persistability invariants as the parse (via `roadmapShapeOk`), deliberately: the gateway is
 * injected, so a caller that wires a different (or missing) validator must not be able to slip past the honesty rules
 * the parser exists to enforce — an empty or one-sided plan labeled `complete`, or a title only the DB would reject.
 */
export function narrowRoadmapOutput(validated: unknown): RoadmapOutput | undefined {
  if (typeof validated !== 'object' || validated === null) return undefined;
  const v = validated as { goals?: unknown; milestones?: unknown; partial?: unknown };
  if (!Array.isArray(v.goals) || !Array.isArray(v.milestones) || typeof v.partial !== 'boolean') return undefined;
  const goals: PlanItemInput[] = [];
  for (const g of v.goals) {
    if (typeof g !== 'object' || g === null) return undefined;
    const { title: t, description: d } = g as { title?: unknown; description?: unknown };
    if (typeof t !== 'string' || (d !== null && typeof d !== 'string')) return undefined;
    goals.push({ title: t, description: d });
  }
  const milestones: MilestoneInput[] = [];
  for (const m of v.milestones) {
    if (typeof m !== 'object' || m === null) return undefined;
    const { title: t, description: d, goalOrdinal: o } = m as { title?: unknown; description?: unknown; goalOrdinal?: unknown };
    if (typeof t !== 'string' || (d !== null && typeof d !== 'string')) return undefined;
    // A validated value always carries an explicit goalOrdinal (parse writes null when unlinked), so `undefined` here
    // means the seam value is corrupted — reject rather than silently unlinking the milestone.
    if (o !== null && (typeof o !== 'number' || !Number.isInteger(o) || o < 0 || o >= goals.length)) return undefined;
    milestones.push({ title: t, description: d, goalOrdinal: o });
  }
  if (!roadmapShapeOk(goals, milestones, v.partial)) return undefined;
  return { goals, milestones, partial: v.partial };
}

/**
 * The bounded reason an owner must supply with a ROAD-002 edit ("record rationale"). REQUIRED — unlike a decision
 * rationale, an edit without a reason loses the "why" the requirement exists to preserve. Returns undefined when
 * absent/blank/over-long, which the caller surfaces as `invalid`.
 */
export function normalizeEditReason(v: unknown): string | undefined {
  if (typeof v !== 'string') return undefined;
  const t = v.trim();
  return t.length === 0 || t.length > EDIT_REASON_MAX ? undefined : t;
}

// ── client-facing views (redacted; no accountId, actor ids, or internal errors) ────────────────────────────
export interface GoalDTO {
  readonly goalId: string;
  readonly ordinal: number;
  readonly title: string;
  readonly description: string | null;
  readonly status: GoalStatus;
}
export interface MilestoneDTO {
  readonly milestoneId: string;
  readonly ordinal: number;
  readonly goalId: string | null;
  readonly title: string;
  readonly description: string | null;
  readonly status: MilestoneStatus;
}
export interface RoadmapDTO {
  readonly roadmapId: string;
  readonly companyId: string;
  readonly version: number;
  readonly decisionId: string;
  readonly status: RoadmapStatus;
  readonly origin: RoadmapOrigin;
  readonly supersedesRoadmapId: string | null;
  readonly editReason: string | null;
  readonly modelFlaggedPartial: boolean;
  readonly goals: readonly GoalDTO[];
  readonly milestones: readonly MilestoneDTO[];
  readonly createdAt: string;
}
