// core/understanding — public index (ACBP-P2-008; CDR-029). Cross-module imports go through this index (spec rule 10).
export {
  generateUnderstanding,
  formatMemoryForPrompt,
  buildUnderstandingRequest,
  type GenerateUnderstandingParams,
  type UnderstandingGenerationDeps,
  type UnderstandingGenerationOptions,
  type GenerateUnderstandingResult,
  type UnderstandingDocumentDTO,
  type UnderstandingSectionDTO,
  type UnderstandingItemDTO,
} from './understanding-generation.js';
export {
  recordUnderstandingReview,
  confirmUnderstanding,
  correctUnderstanding,
  isCurrentUnderstandingConfirmed,
  STRATEGY_DEPENDENT_COUNT,
  type UnderstandingReviewOptions,
  type RecordReviewParams,
  type RecordReviewResult,
  type UnderstandingReviewDTO,
  type ConfirmParams,
  type ConfirmResult,
  type CorrectParams,
  type CorrectResult,
  type GateParams,
  type GateResult,
} from './understanding-review.js';
